### ISSUE TITLE
getShape is depreciated

### ISSUE THREAD

**Issue by zhouzhouthezhou** [Tiph-Studios/DysonSphereProject#40]
According to SonarLint getShape is depreciated and should not be overridden. We should figure out the up to date way to create a slab-ish block

```
    @Override
    public VoxelShape getShape(
            BlockState p_60555_, BlockGetter p_60556_, BlockPos p_60557_, CollisionContext p_60558_) {
        return SHAPE;
    }

```

**Comment by zhouzhouthezhou** [comment]
maybe this is ok idk
![image](https://github.com/Tiph-Studios/DysonSphereProject/assets/16882836/94906259-ddc0-40a5-a1f0-e488d72ed2d0)

**Comment by zhouzhouthezhou** [comment]
I guess action item here is to see how other neoforged mods do it.
I've been using https://vscode.dev/github/JDDev0/EnergizedPower/ as a reference point

**Comment by PJWahlgren** [comment]
Every other mod uses it. Begone!
