### ISSUE TITLE
Solarpanel crash when placed

### ISSUE THREAD

**Issue by PJWahlgren** [Tiph-Studios/DysonSphereProject#48]
SolarGeneratorEntity constructor calls static variable in DysonBlocks which gets it's value from SolarGeneratorEntity's constructor.
![FeelsOkayMan](https://github.com/Tiph-Studios/DysonSphereProject/assets/117400896/c4aae365-bd90-463b-8e8e-9c6599831d8d)

**Comment by zhouzhouthezhou** [comment]
fixed in #49
