### ISSUE TITLE
where mod

### ISSUE THREAD

**Issue by cmpashak** [Tiph-Studios/DysonSphereProject#6]
no dsyons phere

**Comment by cmpashak** [comment]
1. make solar panel
2. texture solar panel
3. give it a recipe
4. make it produce rf

**Comment by zhouzhouthezhou** [comment]
please update your ticket with current status and expected story points @cmpashak

**Comment by cmpashak** [comment]
EXPECTED STORY POINTS: 4

**Comment by zhouzhouthezhou** [comment]
List of stuff needed for MVP

- [block/generator] Solar panel block: generates FE
- [basic item] Orbital Collector: Use solar panels to craft orbital collector
- [block/machine] Warp Dislocator: consumes orbital collector and FE
- [block/generator] Ground station: generates FE proportional to number of orbital collectors consumed
